
image_topic: "image_data"
img_cv_type: 16
pool_size: 256
recv_img_url_root: "tcp://localhost:900"
container_admin_name: "SSW1"
#server_admin_port: 9090
#server_system_port: 9191
num_subscribers: 4
loop_period: 1000
